services:
  postgres:
    image: postgres:15-alpine
    container_name: tiktok-bot-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  tiktok-bot:
    build: .
    container_name: tiktok-downloader-bot
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  bot-network:
    driver: bridge
